DROP TABLE IF exists Meal;
GO

CREATE TABLE Meal (
	MealID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	MealName TEXT NOT NULL,
	MealType VARCHAR(20) NOT NULL,
	MealAddedDate DATETIME2(0),
	CHECK (MealType IN ('Breakfast','Lunch','Dinner', 'Snack'))
)
GO


DROP TABLE IF exists Food
GO

CREATE TABLE Food (
	FoodID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	FoodName VARCHAR(50) NOT NULL UNIQUE,
	FoodType VARCHAR(30) NOT NULL,
	CHECK (FoodType IN ('Regular', 'Junk'))
)
GO


DROP TABLE IF exists FoodMeal
GO

CREATE TABLE FoodMeal (
	MealID UNIQUEIDENTIFIER, 
	FoodID UNIQUEIDENTIFIER,
	FoodQuantity INT,
	PRIMARY KEY (MealID, FoodID),
	FOREIGN KEY (MealID) REFERENCES Meal(MealID) ON DELETE CASCADE,
    FOREIGN KEY (FoodID) REFERENCES Food(FoodID) ON DELETE CASCADE
)


